#include "common_dbc.h"

namespace {

const Signal sigs_1280[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1281[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1282[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1283[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1284[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1285[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1286[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1287[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1288[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1289[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1290[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1291[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1292[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1293[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1294[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1295[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1296[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1297[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1298[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1299[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1300[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1301[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1302[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1303[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1304[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1305[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1306[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1307[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1308[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1309[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1310[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1311[] = {
    {
      .name = "COUNTER",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AZIMUTH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 19,
      .size = 10,
      .is_signed = true,
      .factor = 0.2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_DIST",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_ACCEL",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = true,
      .factor = 0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 34,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 56,
      .size = 14,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};

const Msg msgs[] = {
  {
    .name = "RADAR_TRACK_500",
    .address = 0x500,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1280),
    .sigs = sigs_1280,
  },
  {
    .name = "RADAR_TRACK_501",
    .address = 0x501,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1281),
    .sigs = sigs_1281,
  },
  {
    .name = "RADAR_TRACK_502",
    .address = 0x502,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1282),
    .sigs = sigs_1282,
  },
  {
    .name = "RADAR_TRACK_503",
    .address = 0x503,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1283),
    .sigs = sigs_1283,
  },
  {
    .name = "RADAR_TRACK_504",
    .address = 0x504,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1284),
    .sigs = sigs_1284,
  },
  {
    .name = "RADAR_TRACK_505",
    .address = 0x505,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1285),
    .sigs = sigs_1285,
  },
  {
    .name = "RADAR_TRACK_506",
    .address = 0x506,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1286),
    .sigs = sigs_1286,
  },
  {
    .name = "RADAR_TRACK_507",
    .address = 0x507,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1287),
    .sigs = sigs_1287,
  },
  {
    .name = "RADAR_TRACK_508",
    .address = 0x508,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1288),
    .sigs = sigs_1288,
  },
  {
    .name = "RADAR_TRACK_509",
    .address = 0x509,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1289),
    .sigs = sigs_1289,
  },
  {
    .name = "RADAR_TRACK_50a",
    .address = 0x50A,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1290),
    .sigs = sigs_1290,
  },
  {
    .name = "RADAR_TRACK_50b",
    .address = 0x50B,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1291),
    .sigs = sigs_1291,
  },
  {
    .name = "RADAR_TRACK_50c",
    .address = 0x50C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1292),
    .sigs = sigs_1292,
  },
  {
    .name = "RADAR_TRACK_50d",
    .address = 0x50D,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1293),
    .sigs = sigs_1293,
  },
  {
    .name = "RADAR_TRACK_50e",
    .address = 0x50E,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1294),
    .sigs = sigs_1294,
  },
  {
    .name = "RADAR_TRACK_50f",
    .address = 0x50F,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1295),
    .sigs = sigs_1295,
  },
  {
    .name = "RADAR_TRACK_510",
    .address = 0x510,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1296),
    .sigs = sigs_1296,
  },
  {
    .name = "RADAR_TRACK_511",
    .address = 0x511,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1297),
    .sigs = sigs_1297,
  },
  {
    .name = "RADAR_TRACK_512",
    .address = 0x512,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1298),
    .sigs = sigs_1298,
  },
  {
    .name = "RADAR_TRACK_513",
    .address = 0x513,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1299),
    .sigs = sigs_1299,
  },
  {
    .name = "RADAR_TRACK_514",
    .address = 0x514,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1300),
    .sigs = sigs_1300,
  },
  {
    .name = "RADAR_TRACK_515",
    .address = 0x515,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1301),
    .sigs = sigs_1301,
  },
  {
    .name = "RADAR_TRACK_516",
    .address = 0x516,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1302),
    .sigs = sigs_1302,
  },
  {
    .name = "RADAR_TRACK_517",
    .address = 0x517,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1303),
    .sigs = sigs_1303,
  },
  {
    .name = "RADAR_TRACK_518",
    .address = 0x518,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1304),
    .sigs = sigs_1304,
  },
  {
    .name = "RADAR_TRACK_519",
    .address = 0x519,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1305),
    .sigs = sigs_1305,
  },
  {
    .name = "RADAR_TRACK_51a",
    .address = 0x51A,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1306),
    .sigs = sigs_1306,
  },
  {
    .name = "RADAR_TRACK_51b",
    .address = 0x51B,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1307),
    .sigs = sigs_1307,
  },
  {
    .name = "RADAR_TRACK_51c",
    .address = 0x51C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1308),
    .sigs = sigs_1308,
  },
  {
    .name = "RADAR_TRACK_51d",
    .address = 0x51D,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1309),
    .sigs = sigs_1309,
  },
  {
    .name = "RADAR_TRACK_51e",
    .address = 0x51E,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1310),
    .sigs = sigs_1310,
  },
  {
    .name = "RADAR_TRACK_51f",
    .address = 0x51F,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1311),
    .sigs = sigs_1311,
  },
};

const Val vals[] = {
};

}

const DBC hyundai_kia_mando_front_radar = {
  .name = "hyundai_kia_mando_front_radar",
  .num_msgs = ARRAYSIZE(msgs),
  .msgs = msgs,
  .vals = vals,
  .num_vals = ARRAYSIZE(vals),
};

dbc_init(hyundai_kia_mando_front_radar)